package dk.nodes.template.nstack

import dk.nodes.nstack.kotlin.NStack

/**
 * Generated by the NStack gradle plugin
 */
object RateReminderActions {

	private const val TEST = "test"

	suspend fun test() {
		send(TEST)
	}

	private suspend fun send(action: String) {
		NStack.RateReminder.action(action)
	}
}
