package dk.nodes.template.presentation.nstack

import dk.nodes.nstack.kotlin.NStack

/**
 * Generated by the NStack gradle plugin
 */
object RateReminderActions {


    private suspend fun send(action: String) {
        NStack.RateReminder.action(action)
    }
}
